identifier: my60ble
name: My 60% BLE Keyboard
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - gpio
  - i2c
  - pwm
  - spi
  - watchdog
